id: P005605
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:27.825143
source_metadata:
  id: bdr:W1AC256
  title: 'བོད་ཀྱི་གསོ་རིག་ལས་ལུས་འཚོ་བདེ་སྲུང་སྐོར་གྱི་རྒྱུན་མཁོ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    692eed2b5201462ba47673b1e476f46e:
      image_group_id: I2PD18111
      title: ''
      volume_number: 1
      total_pages: 570
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
