id: ICE60FCC8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:26:07+00:00'
last_modified: '2022-06-08T05:14:27.438348+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC256
  title: 'བོད་ཀྱི་གསོ་རིག་ལས་ལུས་འཚོ་བདེ་སྲུང་སྐོར་གྱི་རྒྱུན་མཁོ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1333':
      image_group_id: I2PD18111
      title: ''
      total_pages: 570
      order: 1
      base_file: 1333.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
